# Generated by Django 5.1.6 on 2025-02-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(default='no data', upload_to='article/'),
            preserve_default=False,
        ),
    ]
