# Generated by Django 5.1.6 on 2025-03-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_login_delete_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
