# Generated by Django 5.1.6 on 2025-04-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_rename_name_ingredient_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='no data'),
            preserve_default=False,
        ),
    ]
